# Generated by Django 5.1.7 on 2025-03-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'Wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('other', 'other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('inital_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'Wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('other', 'other')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('activate', models.BooleanField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
