# Generated by Django 5.1.7 on 2025-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='comment_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productauction',
            name='comment_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
