# Generated by Django 5.1.7 on 2025-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('wool', 'wool'), ('Decoration', 'Decoration'), ('Painting', 'Painting'), ('sweet', 'sweet'), ('Candle', 'Candle'), ('Bags', 'Bags'), ('Carving', 'Carving'), ('other', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
