# Generated by Django 5.1.7 on 2025-04-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_productauction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
