# Generated by Django 5.1.7 on 2025-06-22 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_rate_product_comment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productauction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productauction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
