# Generated by Django 5.1.7 on 2025-06-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productauction',
            old_name='start_date',
            new_name='created_at',
        ),
    ]
