# Generated by Django 5.1.7 on 2025-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_start_date_productauction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='product.product'),
        ),
    ]
