# Generated by Django 5.1.7 on 2025-04-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productauction',
            options={'ordering': ['id']},
        ),
    ]
