# Generated by Django 5.1.7 on 2025-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productauction_buyer_alter_productauction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productauction',
            old_name='inital_price',
            new_name='initial_price',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('auction_end', 'Auction Ended'), ('outbid', 'You Were Outbid'), ('auction_won', 'You Won the Auction')], max_length=20),
        ),
    ]
