# Generated by Django 5.1.7 on 2025-04-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options_alter_productauction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productauction',
            options={},
        ),
    ]
