# Generated by Django 5.1.7 on 2025-08-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='product.productauction'),
        ),
    ]
