# Generated by Django 5.1.7 on 2025-03-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customuser'),
        ),
        migrations.AlterField(
            model_name='productauction',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='product.customuser'),
        ),
        migrations.AlterField(
            model_name='productauction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='product.customuser'),
        ),
    ]
