# Generated by Django 5.1.7 on 2025-08-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_transferrequest_reviewed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
