# Generated by Django 5.1.7 on 2025-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
