# Generated by Django 5.1.7 on 2025-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_notification_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_notified',
        ),
        migrations.AddField(
            model_name='productauction',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
