# Generated by Django 5.1.7 on 2025-04-01 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productauction_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productauction',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productauction',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
