# Generated by Django 5.1.7 on 2025-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productauction_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productauction',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'Wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('other', 'other')], default=2017, max_length=50),
            preserve_default=False,
        ),
    ]
