# Generated by Django 5.1.7 on 2025-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_notification_is_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment_rate',
        ),
        migrations.RemoveField(
            model_name='productauction',
            name='comment_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='negative_comment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='positive_comment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productauction',
            name='negative_comment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productauction',
            name='positive_comment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('other', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productauction',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('other', 'other')], max_length=50),
        ),
    ]
