# Generated by Django 5.1.7 on 2025-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_comment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('auction_end', 'Auction Ended'), ('outbid', 'You Were Outbid'), ('auction_won', 'You Won the Auction'), ('transfer_request', 'The request is pending'), ('transfer_status', 'The transfer status'), ('price_change', 'The price change')], max_length=20),
        ),
    ]
