# Generated by Django 5.1.7 on 2025-09-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('Other', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productauction',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Candle', 'Candle'), ('Painting', 'Painting'), ('Wool', 'wool'), ('Sweet', 'Sweet'), ('Carving', 'Carving'), ('Decoration', 'Decoration'), ('Bags', 'Bags'), ('Other', 'other')], max_length=50),
        ),
    ]
