# Generated by Django 5.1.7 on 2025-04-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productauction_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productauction',
            name='activate',
            field=models.BooleanField(),
        ),
    ]
