# Generated by Django 5.1.7 on 2025-04-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productauction_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productauction',
            name='activate',
        ),
    ]
