# Generated by Django 5.1.7 on 2025-04-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
    ]
