# Generated by Django 5.1.7 on 2025-04-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
    ]
