# Generated by Django 5.1.7 on 2025-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productauction_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
    ]
