# Generated by Django 5.1.7 on 2025-04-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_chat_options'),
        ('product', '0019_alter_product_user'),
    ]

    operations = [
    ]
