# Generated by Django 5.1.7 on 2025-03-26 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('inital_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Carving', 'Carving'), ('Candle', 'Candle'), ('wool', 'wool'), ('sweet', 'sweet'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Decoration', 'Decoration'), ('other', 'other'), ('Painting', 'Painting')], max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
